name: MoonPvPCore
author: DavidDGTNT for MoonPvP
api: [3.0.0]
version: 1.3.1
main: MoonPvPCore\Main

commands:
 spawn:
  description: Sends you back to spawn.
  usage: /spawn
 food:
  description: Gives you the effects of eating food.
  usage: /feed
 hub:
  description: Sends you back to spawn.
  usage: /hub
 lobby:
  description: Sends you back to spawn.
  usage: /lobby